Sparse
UoB-HPC/GPU-BLAS-Offload-Benchmark pull request #1
Opened 2024-02-02 13:53 UTC by ABenC377

Adding in Sparse CPU Kernel.  Currently just runs a square matrix with a sparsity of 0.99 for each problem size.

2024-02-02 14:57 UTC, FinnWilkinson approved these changes
Generally looks good, just a few queries about comments and project structure

2024-02-02 14:58 UTC, FinnWilkinson requested changes
Was meant to request changes last time...

2024-02-16 07:46 UTC, FinnWilkinson requested changes

2026-04-20 14:42 UTC, closed without merging

2026-04-20 14:42 UTC, ABenC377 commented
Made a lot of changes to the branch, so closing and starting again